from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 461, 131))

        font = QtGui.QFont() 
        font.setFamily("Arial")
        font.setPointSize(24)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")

        self.Cbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Cbutton.setGeometry(QtCore.QRect(10, 160, 100, 100))
        

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Cbutton.setFont(font)
        self.Cbutton.setObjectName("Cbutton")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(250, 270, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(130, 270, 100, 100))


        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 270, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(370, 160, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(250, 160, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.percent.setFont(font)
        self.percent.setObjectName("percent")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(370, 270, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(10, 490, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(130, 490, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(10, 380, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(130, 380, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(250, 380, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(370, 380, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.subtract.setFont(font)
        self.subtract.setObjectName("subtract")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(250, 490, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(370, 490, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(130, 600, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.deci = QtWidgets.QPushButton(self.centralwidget)
        self.deci.setGeometry(QtCore.QRect(130, 160, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deci.setFont(font)
        self.deci.setObjectName("deci")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setEnabled(True)
        self.equal.setGeometry(QtCore.QRect(249, 600, 221, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.integer = QtWidgets.QPushButton(self.centralwidget)
        self.integer.setGeometry(QtCore.QRect(10, 600, 100, 100))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.integer.setFont(font)
        self.integer.setObjectName("integer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 22))
        
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calc"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.Cbutton.setText(_translate("MainWindow", "C"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.multiply.setText(_translate("MainWindow", "x"))
        self.three.setText(_translate("MainWindow", "3"))
        self.two.setText(_translate("MainWindow", "2"))
        self.six.setText(_translate("MainWindow", "6"))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.subtract.setText(_translate("MainWindow", "-"))
        self.one.setText(_translate("MainWindow", "1"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.deci.setText(_translate("MainWindow", "."))
        self.equal.setText(_translate("MainWindow", "="))
        self.integer.setText(_translate("MainWindow", "+/-"))

    def press(self, pressed):
        self.outputLabel.setText(pressed)
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

